### ISSUE TITLE
Submit an Escalation

### ISSUE THREAD

**Issue by arsidada** [maxgala/aspire-frontend#164]
- [ ] Add button on User Dashboard view to submit an escalation
- [ ] Add a modal where escalation details are gathered like:
    - [ ] User (this we can get from the browser)
    - [ ] Title
    - [ ] Type of escalation - a small list of types of escalations
    - [ ] Description- explanation of the issue. need to add a character limit
- [ ] On submit, send email with contents to aspire@maxgala.com
- [ ] Prepend the email subject with `[ESCALATION] -` and then the title the user provided. This will make it easy for the ops team to filter on the email in their inbox.
- [ ] Design needs to looks similar to this:
https://xd.adobe.com/view/f15de1d8-f177-4b9a-8e15-bbf56bf78584-a40e/screen/f2da35f3-428a-4ec9-bc69-d841e97b25bd/
![image](https://user-images.githubusercontent.com/1714180/94822999-53911f80-03d1-11eb-8026-ef6d07e59cc3.png)

**Comment by ahaq0** [comment]
This has been merged to master.
