### ISSUE TITLE
Don't handle empty response from Chats API, app crashes 

### ISSUE THREAD

**Issue by ahaq0** [maxgala/aspire-frontend#196]
Currently on master, if a user has no chats, the chats response will be undefined and we'll try to parse it causing the application to crash right after logging in best seen here. https://i.imgur.com/pAeZzFw.png.

Tested with the following account ahmed.r.hamodi@gmail.com.

**Comment by ahaq0** [comment]
Simple fix for now, checking response see branch ammarHotfix196ChatsResponse

**Comment by ahmedhamodi** [comment]
Good catch, can you create a PR for this and I can review?
