### ISSUE TITLE
Error handling for Registration

### ISSUE THREAD

**Issue by arsidada** [maxgala/aspire-frontend#201]
- [x] Password requirements need to be met before they can continue next page.
- [x] Bday Year, can it be constraint to 4 numbers?
- [x] Add field for City
- [x] Make resume/pic mandatory
- [x] Ensure that the same email cannot be used to sign up again. Ideally, when the user enters an email already used then they are given the error right away instead of at the end of sign up. This can be either when they complete writing out their email in the form field or when they hit NEXT (whichever is easier)
- [x] Email needs to be isEmail.. ‘abc@abc’ is allowed right now but is not correct.
- [x] Remove MAX logo at the top of the registration form as it's redundant. Make sure alignment with top banner is still ok

**Comment by riztaha** [comment]
Already registered email cannot be used again, user is notified on final page of registration instead of immediately (this might actually be better for security reasons, someone could potentially get all of our registered emails if there was an immediate check.)
